---

version: '3.7'

services:
  db:
    image: postgres:12.2
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_DB=hs-dev
      - POSTGRES_PASSWORD=docker
  test:
    build:
      context: .
      dockerfile: Dockerfile
    command: lein test
    depends_on:
      - db

volumes:
  pgdata:
