apiVersion: apps/v1
kind: Deployment
metadata:
  name: clojure-web
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: app
        image: docker.pkg.github.com/nikitanaumenko/simple-clojure-crud/app:latest
        ports:
          - containerPort: 3000
        envFrom:
          - configMapRef:
              name: app-config-map
        command:
          - make
          - prod-start
      - name: caddy
        image: docker.pkg.github.com/nikitanaumenko/simple-clojure-crud/caddy:latest
        ports:
        - containerPort: 443
      imagePullSecrets:
        - name: regsecret

