apiVersion: v1
kind: Pod
metadata:
  name: simple-clojure-crud-pod
  labels:
    app: simple-clojure-crud
spec:
  containers:
  - name: app
    image: docker.pkg.github.com/nikitanaumenko/simple-clojure-crud/app:latest
    ports:
    - containerPort: 3000
  - name: caddy
    image: docker.pkg.github.com/nikitanaumenko/simple-clojure-crud/caddy:latest
    ports:
    - containerPort: 443
  imagePullSecrets:
    - name: regsecret
