apiVersion: v1
kind: Service
metadata:
  name: simple-clojure-crud-svc
  labels:
    app: simple-clojure-crud
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
  selector:
    app: simple-clojure-crud
