---

version: '3.3'

services:
  db:
    image: postgres:12.2
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_DB=hs-test
      - POSTGRES_PASSWORD=docker
  test:
    build:
      context: .
      dockerfile: Dockerfile
    command: clj -Atest
    env_file:
      - './.env.test'
    depends_on:
      - db

volumes:
  pgdata:
