---

version: '3.3'

services:
  db:
    image: postgres:12.2
    environment: 
     - POSTGRES_DB=test-db
     - "POSTGRES_HOST_AUTH_METHOD=trust"

    network_mode: host
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    command: make test-t
    environment:
      - CLJ_ENV=test
    env_file:
      - './.env.test'
    network_mode: host
    depends_on:
      - db

volumes:
  pgdata:
