name: On Push

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run web tests
      run: |
        make test-ci

    - name: Setup Clojure
    - uses: DeLaGuardo/setup-clojure@2.0
      with:
        tools-deps: '1.10.1.469'

    - name: Build jar
      run: |
        make build-jar
    - name: Login to Docker Hub
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login -u "${{ secrets.NICKNAME }}" --password-stdin docker.pkg.github.com
    - name: Build
      run: make app-docker-build-production
    - name: Push
      run: make app-docker-push
    - name: Build Caddy
      run: make caddy-docker-build-production
    - name: Push Caddy
      run: make caddy-docker-push
